# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='picture',
            field=models.CharField(default='', max_length=300),
        ),
    ]
