# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heroes', '0002_heroes_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
